name: tunceducationn
description: A new Flutter project.

publish_to: "none"

version: 1.6.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  badges: ^3.1.2
  bloc: ^8.1.2
  chewie: ^1.7.0
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fake_cloud_firestore: ^3.0.3
  file_picker: ^8.1.2
  firebase_auth: ^5.3.1
  firebase_auth_mocks: ^0.14.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_storage_mocks: ^0.7.0
  # firebase_ui_auth: ^1.6.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_link_previewer: ^3.2.2
  flutter_tindercard:
    git:
      url: https://github.com/NonymousMorlock/flutter_tindercard.git
  flutter_screenutil: ^5.8.4
  font_awesome_flutter: ^10.5.0
  get_it: ^8.0.0
  google_sign_in_mocks: ^0.3.0
  iconly: ^1.0.1
  image_picker: ^1.0.2
  intl: ^0.19.0
  lottie: ^3.0.0
  open_file: ^3.3.2
  path_provider: ^2.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  step_progress_indicator: ^1.0.2
  swipe_to: ^1.0.2
  url_launcher: ^6.1.12
  uuid: ^4.1.0
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
